import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../infra/database/prisma.service';

@Injectable()
export class ScansPdfService {
  constructor(private prisma: PrismaService) {}

  async generateHtml(scanId: string, userId: string): Promise<string> {
    const scan = await this.prisma.scan.findFirst({
      where: { id: scanId, userId },
      include: { ingredients: { orderBy: { position: 'asc' } } },
    });
    if (!scan) throw new NotFoundException('Scan not found');

    const raw = (scan.rawResponse as Record<string, unknown>) ?? {};
    const summary = (raw['summary'] as string) ?? '';
    const flagged = (raw['flaggedIngredients'] as Array<Record<string, string>>) ?? [];

    const bandColor: Record<string, string> = {
      excellent: '#0D4A2E',
      good: '#2ABF6A',
      caution: '#D6A443',
      poor: '#D9764A',
      avoid: '#B5412F',
    };

    const flaggedRows = flagged
      .map(
        (f) =>
          `<tr>
            <td style="padding:8px 12px;border-bottom:1px solid #eee;">${f['name'] ?? ''}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #eee;color:${bandColor[f['band'] ?? 'caution'] ?? '#D6A443'};font-weight:600;text-transform:capitalize;">${f['band'] ?? 'caution'}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #eee;color:#6A6F64;">${f['reason'] ?? ''}</td>
          </tr>`,
      )
      .join('');

    const ingredientRows = scan.ingredients
      .map(
        (ing) =>
          `<tr>
            <td style="padding:6px 12px;border-bottom:1px solid #f0f0f0;">${ing.name}</td>
            <td style="padding:6px 12px;border-bottom:1px solid #f0f0f0;color:${bandColor[ing.riskLevel.toLowerCase()] ?? '#D6A443'};font-weight:600;text-transform:capitalize;">${ing.riskLevel.toLowerCase()}</td>
            <td style="padding:6px 12px;border-bottom:1px solid #f0f0f0;color:#6A6F64;font-size:13px;">${ing.reason ?? ''}</td>
          </tr>`,
      )
      .join('');

    const scoreColor = bandColor[scan.band?.toLowerCase() ?? 'caution'] ?? '#D6A443';

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Clera Scan Report — ${scan.productName ?? 'Product'}</title>
<style>
  body { font-family: -apple-system, sans-serif; color: #12130F; margin: 0; padding: 32px; background: #F7F4EC; }
  .header { display:flex; align-items:center; margin-bottom:32px; }
  .logo { font-size:22px; font-weight:700; color:#0D4A2E; letter-spacing:-0.5px; }
  .logo span { color:#4EE890; }
  .score-ring { width:80px; height:80px; border-radius:50%; background:${scoreColor}; display:flex; align-items:center; justify-content:center; color:#fff; font-size:28px; font-weight:700; margin-left:auto; }
  h1 { font-size:24px; font-weight:700; margin:0 0 4px; }
  .meta { color:#6A6F64; font-size:13px; margin-bottom:24px; }
  .summary { background:#fff; border-radius:12px; padding:16px 20px; margin-bottom:24px; line-height:1.6; border:1px solid #E4DFD1; }
  h2 { font-size:14px; font-weight:600; text-transform:uppercase; letter-spacing:1.5px; color:#6A6F64; margin:24px 0 12px; }
  table { width:100%; border-collapse:collapse; background:#fff; border-radius:12px; overflow:hidden; border:1px solid #E4DFD1; }
  th { padding:10px 12px; text-align:left; font-size:11px; text-transform:uppercase; letter-spacing:1px; color:#6A6F64; background:#F7F4EC; border-bottom:1px solid #E4DFD1; }
  .footer { margin-top:48px; color:#6A6F64; font-size:12px; text-align:center; }
</style>
</head>
<body>
  <div class="header">
    <div>
      <div class="logo">CLERA<span>.</span></div>
      <div style="font-size:11px;color:#6A6F64;margin-top:2px;">Ingredient Safety Report</div>
    </div>
    <div class="score-ring">${scan.score}</div>
  </div>

  <h1>${scan.productName ?? 'Product'}</h1>
  <div class="meta">${scan.category ?? ''} · Scanned ${new Date(scan.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div>

  ${summary ? `<div class="summary">${summary}</div>` : ''}

  ${flaggedRows ? `<h2>Watch out for</h2>
  <table>
    <thead><tr><th>Ingredient</th><th>Rating</th><th>Why</th></tr></thead>
    <tbody>${flaggedRows}</tbody>
  </table>` : ''}

  <h2>All ${scan.ingredients.length} ingredients</h2>
  <table>
    <thead><tr><th>Name</th><th>Safety</th><th>Notes</th></tr></thead>
    <tbody>${ingredientRows}</tbody>
  </table>

  <div class="footer">
    Generated by Clera · clera.app · ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}<br>
    For educational purposes only — not medical advice.
  </div>
</body>
</html>`;
  }
}
