import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../core/theme/app_theme.dart';
import '../../../shared/widgets/ss_primitives.dart';

class PoliciesScreen extends ConsumerStatefulWidget {
  const PoliciesScreen({super.key});

  @override
  ConsumerState<PoliciesScreen> createState() => _PoliciesScreenState();
}

class _PoliciesScreenState extends ConsumerState<PoliciesScreen> {
  final Set<String> _expanded = {'ai_disclaimer'};

  void _toggle(String key) =>
      setState(() => _expanded.contains(key) ? _expanded.remove(key) : _expanded.add(key));

  bool _isExpanded(String key) => _expanded.contains(key);

  @override
  Widget build(BuildContext context) {
    final dark = Theme.of(context).brightness == Brightness.dark;
    final brand = dark ? SSColors.forestDark : SSColors.forest;

    return Scaffold(
      backgroundColor: dark ? SSColors.bgDark : SSColors.paper,
      body: SafeArea(
        child: Column(
          children: [
            SSTopBar(
              leading: SSIconBtn(
                icon: Icons.arrow_back_ios_new_rounded,
                onTap: () => context.pop(),
              ),
              title: 'Policies & Legal',
            ),
            Expanded(
              child: ListView(
                padding: const EdgeInsets.symmetric(horizontal: 20),
                children: [
                  const SizedBox(height: 8),

                  // Version banner
                  _VersionBanner(dark: dark, brand: brand),
                  const SizedBox(height: 28),

                  // ── AI ACCURACY DISCLAIMER ─────────────────────────────
                  _SectionLabel('AI ACCURACY DISCLAIMER', dark: dark),
                  const SizedBox(height: 8),
                  _ExpandableCard(
                    sectionKey: 'ai_disclaimer',
                    dark: dark,
                    brand: brand,
                    expanded: _isExpanded('ai_disclaimer'),
                    onToggle: () => _toggle('ai_disclaimer'),
                    title: 'Important — Results are AI-generated',
                    badge: 'Read this',
                    badgeColor: SSColors.caution,
                    preview: 'Clera uses AI to analyse ingredient labels. Results may be incomplete or inaccurate.',
                    body: const [
                      _PolicyPara(
                        'Clera uses artificial intelligence (Claude by Anthropic) to read and interpret ingredient labels captured through your camera. While we strive for accuracy, AI systems can make mistakes.',
                      ),
                      _PolicyBullet('The AI may misread, omit, or misclassify ingredients.'),
                      _PolicyBullet('Scores and safety ratings are indicative only — not a definitive safety certification.'),
                      _PolicyBullet('Results depend on label quality, lighting, and the completeness of the captured image.'),
                      _PolicyBullet('Ingredient databases and safety classifications are updated periodically but may not reflect the latest research.'),
                      _PolicyPara(
                        'Clera is NOT a substitute for professional medical, nutritional, or pharmaceutical advice. Always consult a qualified professional before making decisions about your health based on scan results.',
                      ),
                      _PolicyPara(
                        'IMPORTANT — MANUFACTURER & BRAND LIABILITY: Scan results generated by Clera do not represent the views, claims, or endorsements of the product manufacturer or brand. Clera is an independent third-party tool. Product manufacturers bear no responsibility for the accuracy of Clera\'s AI-generated analysis. If you believe a result is incorrect, please use the "Report an issue" option on the result screen.',
                      ),
                      _PolicyPara(
                        'By using Clera, you acknowledge and agree that Clera Labs and its affiliates are not liable for any decisions made based on AI-generated scan results.',
                      ),
                    ],
                  ),
                  const SizedBox(height: 28),

                  // ── TERMS OF SERVICE ───────────────────────────────────
                  _SectionLabel('TERMS OF SERVICE', dark: dark),
                  const SizedBox(height: 8),
                  _ExpandableCard(
                    sectionKey: 'terms',
                    dark: dark,
                    brand: brand,
                    expanded: _isExpanded('terms'),
                    onToggle: () => _toggle('terms'),
                    title: 'Terms of Service',
                    preview: 'By using Clera you agree to these terms. Please read them carefully.',
                    body: const [
                      _PolicyHeading('1. Acceptance of Terms'),
                      _PolicyPara(
                        'By downloading, installing, or using Clera ("the App"), you agree to be bound by these Terms of Service. If you do not agree, do not use the App.',
                      ),
                      _PolicyHeading('2. Description of Service'),
                      _PolicyPara(
                        'Clera provides AI-powered ingredient label scanning and safety analysis for food, cosmetic, medicine, and household products. The service is provided for informational purposes only.',
                      ),
                      _PolicyHeading('3. Eligibility'),
                      _PolicyPara(
                        'You must be at least 13 years old to use Clera. By using the App you represent that you meet this requirement.',
                      ),
                      _PolicyHeading('4. User Accounts'),
                      _PolicyPara(
                        'You are responsible for maintaining the confidentiality of your account. You are responsible for all activity that occurs under your account. Notify us immediately at hello@clera.app if you suspect unauthorised use.',
                      ),
                      _PolicyHeading('5. Acceptable Use'),
                      _PolicyBullet('Do not use Clera to spread false or misleading information about products or their manufacturers.'),
                      _PolicyBullet('Do not reverse-engineer, decompile, or attempt to extract the source code of the App.'),
                      _PolicyBullet('Do not use automated tools to scrape or bulk-query the service.'),
                      _PolicyBullet('Do not use the App in any way that violates applicable Indian or international law.'),
                      _PolicyHeading('6. AI-Generated Content Disclaimer'),
                      _PolicyPara(
                        'All scan results are generated by AI and are provided "as is" without warranty of any kind. Clera makes no representations about the accuracy, completeness, or reliability of any scan result. See the AI Accuracy Disclaimer section for full details.',
                      ),
                      _PolicyHeading('7. Intellectual Property'),
                      _PolicyPara(
                        'The Clera name, logo, design, and all associated content are the property of Clera Labs. You may not use them without written permission.',
                      ),
                      _PolicyHeading('8. Limitation of Liability'),
                      _PolicyPara(
                        'To the maximum extent permitted by law, Clera Labs shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the App or reliance on any scan result.',
                      ),
                      _PolicyHeading('9. Termination'),
                      _PolicyPara(
                        'We reserve the right to suspend or terminate your account at any time if you violate these Terms.',
                      ),
                      _PolicyHeading('10. Governing Law'),
                      _PolicyPara(
                        'These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in Trivandrum, Kerala.',
                      ),
                      _PolicyHeading('11. Changes to Terms'),
                      _PolicyPara(
                        'We may update these Terms from time to time. Continued use of the App after changes constitutes acceptance of the new Terms.',
                      ),
                      _PolicyPara('Last updated: May 2026 · Contact: hello@clera.app'),
                    ],
                  ),
                  const SizedBox(height: 28),

                  // ── PRIVACY POLICY ─────────────────────────────────────
                  _SectionLabel('PRIVACY POLICY', dark: dark),
                  const SizedBox(height: 8),
                  _ExpandableCard(
                    sectionKey: 'privacy',
                    dark: dark,
                    brand: brand,
                    expanded: _isExpanded('privacy'),
                    onToggle: () => _toggle('privacy'),
                    title: 'Privacy Policy',
                    preview: 'What we collect, why, and how long we keep it.',
                    body: const [
                      _PolicyHeading('What we collect'),
                      _PolicyBullet('Email address (for sign-in via OTP)'),
                      _PolicyBullet('Name and optional profile details you provide'),
                      _PolicyBullet('Allergen and dietary flags you set in your profile'),
                      _PolicyBullet('Images captured for scanning (sent to our server for AI processing, not stored unless you save the scan)'),
                      _PolicyBullet('Scan history (if you choose to save scans)'),
                      _PolicyBullet('Subscription status (via App Store / Play Store)'),
                      _PolicyBullet('Basic usage analytics (crash reports, feature usage via Sentry — no personal data)'),
                      _PolicyHeading('What we do NOT collect'),
                      _PolicyBullet('We do not collect your precise location.'),
                      _PolicyBullet('We do not sell your data to brands, advertisers, or third parties.'),
                      _PolicyBullet('We do not read your camera roll or any files outside of in-session scan captures.'),
                      _PolicyHeading('How we use your data'),
                      _PolicyPara(
                        'Your data is used solely to provide the Clera service: authenticating you, personalising scan results against your allergen profile, and maintaining your scan history. We use Supabase (EU/US infrastructure) for authentication and data storage, and Anthropic\'s Claude API for AI analysis. Both providers are contractually bound to keep your data confidential.',
                      ),
                      _PolicyHeading('Data retention'),
                      _PolicyPara(
                        'Your data is retained while your account is active. If you delete your account, all personal data is permanently erased after a 30-day grace period. Anonymised aggregate analytics data may be retained indefinitely.',
                      ),
                      _PolicyHeading('Your rights'),
                      _PolicyPara(
                        'Under India\'s DPDP Act 2023 and applicable law, you have the right to access, correct, and delete your data. Use the "Submit a request" button at the bottom of this page.',
                      ),
                      _PolicyPara('Contact: hello@clera.app · Last updated: May 2026'),
                    ],
                  ),
                  const SizedBox(height: 28),

                  // ── HEALTH & SAFETY ────────────────────────────────────
                  _SectionLabel('HEALTH & SAFETY', dark: dark),
                  const SizedBox(height: 8),
                  _ExpandableCard(
                    sectionKey: 'health',
                    dark: dark,
                    brand: brand,
                    expanded: _isExpanded('health'),
                    onToggle: () => _toggle('health'),
                    title: 'Medical & health disclaimer',
                    badge: 'Important',
                    badgeColor: SSColors.caution,
                    preview: 'Clera is not medical advice. Do not rely on scan results for health decisions.',
                    body: const [
                      _PolicyPara(
                        'Clera is a consumer information tool. It is not a medical device, pharmaceutical guide, or dietitian service.',
                      ),
                      _PolicyBullet('Do not use scan results to diagnose, treat, or manage any health condition.'),
                      _PolicyBullet('If you have a severe allergy or medical condition, always read the physical label and consult your doctor or pharmacist.'),
                      _PolicyBullet('Allergen alerts in Clera are based on ingredients detected by AI — they may miss ingredients not visible in the scan or listed in non-standard formats.'),
                      _PolicyBullet('Medicine scans are for general ingredient awareness only. Always follow the advice of a qualified healthcare professional.'),
                      _PolicyPara(
                        'Clera Labs expressly disclaims all liability for any health outcomes arising from reliance on scan results.',
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),
                  _ExpandableCard(
                    sectionKey: 'scoring',
                    dark: dark,
                    brand: brand,
                    expanded: _isExpanded('scoring'),
                    onToggle: () => _toggle('scoring'),
                    title: 'How ingredient scoring works',
                    preview: 'Our AI scores each ingredient against safety databases and your profile.',
                    body: const [
                      _PolicyPara(
                        'Each ingredient is scored by Claude AI against publicly available safety data including FSSAI regulations, EU food additive classifications, EWG cosmetics data, and peer-reviewed literature.',
                      ),
                      _PolicyBullet('Scores range from Excellent (green) to Avoid (red) based on safety evidence strength.'),
                      _PolicyBullet('Your personal profile (allergens, dietary flags) adjusts the result for you specifically.'),
                      _PolicyBullet('The overall product score is a weighted average — it does not mean a product with one "Avoid" ingredient is dangerous overall.'),
                      _PolicyBullet('Scores reflect the AI\'s interpretation of available evidence at the time of scanning. They are not regulatory approvals or safety certifications.'),
                      _PolicyPara(
                        'We update our scoring logic periodically. Historical scan scores may differ from re-scans of the same product.',
                      ),
                    ],
                  ),
                  const SizedBox(height: 28),

                  // ── SUBSCRIPTIONS & REFUNDS ────────────────────────────
                  _SectionLabel('SUBSCRIPTIONS & REFUNDS', dark: dark),
                  const SizedBox(height: 8),
                  _ExpandableCard(
                    sectionKey: 'subscriptions',
                    dark: dark,
                    brand: brand,
                    expanded: _isExpanded('subscriptions'),
                    onToggle: () => _toggle('subscriptions'),
                    title: 'Subscription & refund policy',
                    preview: '14-day refund window · Cancel anytime · GST applies for India.',
                    body: const [
                      _PolicyHeading('Plans'),
                      _PolicyBullet('Free: 5 scans per day, basic results.'),
                      _PolicyBullet('Pro Monthly (₹299/month): unlimited scans, full ingredient breakdown, family profiles.'),
                      _PolicyBullet('Pro Annual (₹2,999/year): same as monthly, best value.'),
                      _PolicyHeading('Billing'),
                      _PolicyPara(
                        'Subscriptions are billed through the Apple App Store or Google Play Store. Clera does not store your payment details. Prices include applicable GST for India.',
                      ),
                      _PolicyHeading('Cancellation'),
                      _PolicyPara(
                        'You can cancel anytime from your App Store / Play Store subscription settings or from the Profile screen in the app. Cancellation stops future renewals. You retain Pro access until the end of your current billing period.',
                      ),
                      _PolicyHeading('Refunds'),
                      _PolicyPara(
                        'We offer a 14-day no-questions refund from the date of purchase. To request a refund, contact hello@clera.app within 14 days. Refunds are processed through the App Store or Play Store and may take 5–10 business days. After 14 days, refunds are at our discretion.',
                      ),
                      _PolicyHeading('Free trial'),
                      _PolicyPara(
                        'If a free trial is offered, cancellation before the trial ends will not result in a charge. If you do not cancel, the subscription converts automatically at the listed price.',
                      ),
                    ],
                  ),
                  const SizedBox(height: 28),

                  // ── ABOUT THIS APP ─────────────────────────────────────
                  _SectionLabel('ABOUT THIS APP', dark: dark),
                  const SizedBox(height: 8),
                  SSCard(
                    padding: EdgeInsets.zero,
                    child: Column(
                      children: [
                        _SimpleRow(
                          dark: dark,
                          title: 'Open-source licenses',
                          hint: 'Flutter, Riverpod, Supabase, and others',
                        ),
                        _SimpleRow(
                          dark: dark,
                          title: 'Accessibility',
                          hint: 'Supports system font size and high contrast',
                        ),
                        _SimpleRow(
                          dark: dark,
                          title: 'Contact us',
                          hint: 'hello@clera.app',
                        ),
                        _SimpleRow(
                          dark: dark,
                          title: 'Registered',
                          hint: 'Clera Labs · Trivandrum, Kerala, India',
                          last: true,
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 28),

                  // ── DPDP / GDPR REQUEST ────────────────────────────────
                  _DataRequestCard(dark: dark, brand: brand),
                  const SizedBox(height: 32),

                  Center(
                    child: Text(
                      'CLERA POLICIES · v1.0 · MAY 2026',
                      style: TextStyle(
                        fontFamily: SSTypography.monoFamily,
                        fontSize: 10,
                        letterSpacing: 1.5,
                        color: dark ? SSColors.mutedDark : SSColors.muted,
                      ),
                    ),
                  ),
                  const SizedBox(height: 24),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ─── Version banner ───────────────────────────────────────────────────────────

class _VersionBanner extends StatelessWidget {
  const _VersionBanner({required this.dark, required this.brand});
  final bool dark;
  final Color brand;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: brand.withValues(alpha: dark ? 0.12 : 0.07),
        borderRadius: SSRadius.borderLg,
        border: Border.all(color: brand.withValues(alpha: dark ? 0.25 : 0.18)),
      ),
      child: Row(
        children: [
          Container(
            width: 36,
            height: 36,
            decoration: BoxDecoration(
              color: brand.withValues(alpha: 0.15),
              borderRadius: SSRadius.borderSm,
            ),
            child: Icon(Icons.verified_outlined, size: 18, color: brand),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'v1.0 · Effective May 2026',
                  style: TextStyle(
                    fontFamily: SSTypography.displayFamily,
                    fontWeight: FontWeight.w700,
                    fontSize: 14,
                    color: dark ? SSColors.inkDark : SSColors.ink,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  'Tap any section to read the full policy.',
                  style: TextStyle(
                    fontFamily: SSTypography.bodyFamily,
                    fontSize: 12.5,
                    color: dark ? SSColors.mutedDark : SSColors.muted,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ─── Expandable card ──────────────────────────────────────────────────────────

class _ExpandableCard extends StatelessWidget {
  const _ExpandableCard({
    required this.sectionKey,
    required this.dark,
    required this.brand,
    required this.expanded,
    required this.onToggle,
    required this.title,
    required this.preview,
    required this.body,
    this.badge,
    this.badgeColor,
  });

  final String sectionKey;
  final bool dark;
  final Color brand;
  final bool expanded;
  final VoidCallback onToggle;
  final String title;
  final String preview;
  final List<Widget> body;
  final String? badge;
  final Color? badgeColor;

  @override
  Widget build(BuildContext context) {
    return SSCard(
      padding: EdgeInsets.zero,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          GestureDetector(
            onTap: onToggle,
            behavior: HitTestBehavior.opaque,
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Expanded(
                              child: Text(
                                title,
                                style: TextStyle(
                                  fontFamily: SSTypography.displayFamily,
                                  fontWeight: FontWeight.w600,
                                  fontSize: 15,
                                  color: dark ? SSColors.inkDark : SSColors.ink,
                                ),
                              ),
                            ),
                            if (badge != null && badgeColor != null) ...[
                              const SizedBox(width: 8),
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                                decoration: BoxDecoration(
                                  color: badgeColor!.withValues(alpha: 0.15),
                                  borderRadius: SSRadius.borderFull,
                                  border: Border.all(color: badgeColor!.withValues(alpha: 0.3)),
                                ),
                                child: Text(
                                  badge!,
                                  style: TextStyle(
                                    fontFamily: SSTypography.bodyFamily,
                                    fontSize: 11,
                                    fontWeight: FontWeight.w600,
                                    color: badgeColor,
                                  ),
                                ),
                              ),
                            ],
                          ],
                        ),
                        if (!expanded) ...[
                          const SizedBox(height: 4),
                          Text(
                            preview,
                            style: TextStyle(
                              fontFamily: SSTypography.bodyFamily,
                              fontSize: 12.5,
                              color: dark ? SSColors.mutedDark : SSColors.muted,
                            ),
                          ),
                        ],
                      ],
                    ),
                  ),
                  const SizedBox(width: 8),
                  Icon(
                    expanded
                        ? Icons.keyboard_arrow_up_rounded
                        : Icons.keyboard_arrow_down_rounded,
                    size: 20,
                    color: dark ? SSColors.mutedDark : SSColors.muted,
                  ),
                ],
              ),
            ),
          ),
          if (expanded) ...[
            Divider(
              height: 1,
              thickness: 1,
              color: dark ? SSColors.lineDark : SSColors.line,
            ),
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 14, 16, 16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: body,
              ),
            ),
          ],
        ],
      ),
    );
  }
}

// ─── Body content widgets ─────────────────────────────────────────────────────

class _PolicyPara extends StatelessWidget {
  const _PolicyPara(this.text);
  final String text;

  @override
  Widget build(BuildContext context) {
    final dark = Theme.of(context).brightness == Brightness.dark;
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Text(
        text,
        style: TextStyle(
          fontFamily: SSTypography.bodyFamily,
          fontSize: 13.5,
          height: 1.55,
          color: dark ? SSColors.ink2Dark : SSColors.ink2,
        ),
      ),
    );
  }
}

class _PolicyHeading extends StatelessWidget {
  const _PolicyHeading(this.text);
  final String text;

  @override
  Widget build(BuildContext context) {
    final dark = Theme.of(context).brightness == Brightness.dark;
    return Padding(
      padding: const EdgeInsets.only(bottom: 6, top: 4),
      child: Text(
        text,
        style: TextStyle(
          fontFamily: SSTypography.displayFamily,
          fontSize: 13.5,
          fontWeight: FontWeight.w600,
          color: dark ? SSColors.inkDark : SSColors.ink,
        ),
      ),
    );
  }
}

class _PolicyBullet extends StatelessWidget {
  const _PolicyBullet(this.text);
  final String text;

  @override
  Widget build(BuildContext context) {
    final dark = Theme.of(context).brightness == Brightness.dark;
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.only(top: 6),
            child: Container(
              width: 5,
              height: 5,
              decoration: BoxDecoration(
                color: dark ? SSColors.mutedDark : SSColors.muted,
                shape: BoxShape.circle,
              ),
            ),
          ),
          const SizedBox(width: 10),
          Expanded(
            child: Text(
              text,
              style: TextStyle(
                fontFamily: SSTypography.bodyFamily,
                fontSize: 13.5,
                height: 1.5,
                color: dark ? SSColors.ink2Dark : SSColors.ink2,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ─── Simple info row ──────────────────────────────────────────────────────────

class _SimpleRow extends StatelessWidget {
  const _SimpleRow({
    required this.dark,
    required this.title,
    this.hint,
    this.last = false,
  });

  final bool dark;
  final String title;
  final String? hint;
  final bool last;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      decoration: last
          ? null
          : BoxDecoration(
              border: Border(
                bottom: BorderSide(color: dark ? SSColors.lineDark : SSColors.line),
              ),
            ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyle(
              fontFamily: SSTypography.bodyFamily,
              fontSize: 14,
              fontWeight: FontWeight.w600,
              color: dark ? SSColors.inkDark : SSColors.ink,
            ),
          ),
          if (hint != null) ...[
            const SizedBox(height: 2),
            Text(
              hint!,
              style: TextStyle(
                fontFamily: SSTypography.bodyFamily,
                fontSize: 12,
                color: dark ? SSColors.mutedDark : SSColors.muted,
              ),
            ),
          ],
        ],
      ),
    );
  }
}

// ─── Data request card ────────────────────────────────────────────────────────

class _DataRequestCard extends StatelessWidget {
  const _DataRequestCard({required this.dark, required this.brand});
  final bool dark;
  final Color brand;

  @override
  Widget build(BuildContext context) {
    return SSCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                width: 36,
                height: 36,
                decoration: BoxDecoration(
                  color: brand.withValues(alpha: 0.12),
                  borderRadius: SSRadius.borderSm,
                ),
                child: Icon(Icons.gavel_rounded, size: 18, color: brand),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'DPDP / GDPR Data Rights',
                      style: TextStyle(
                        fontFamily: SSTypography.displayFamily,
                        fontWeight: FontWeight.w700,
                        fontSize: 14,
                        color: dark ? SSColors.inkDark : SSColors.ink,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Access, correct, or delete your personal data.',
                      style: TextStyle(
                        fontFamily: SSTypography.bodyFamily,
                        fontSize: 12,
                        color: dark ? SSColors.mutedDark : SSColors.muted,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 14),
          GestureDetector(
            onTap: () {},
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 13),
              decoration: BoxDecoration(
                color: brand.withValues(alpha: 0.1),
                borderRadius: SSRadius.borderMd,
                border: Border.all(color: brand.withValues(alpha: 0.3)),
              ),
              child: Center(
                child: Text(
                  'Submit a request · hello@clera.app',
                  style: TextStyle(
                    fontFamily: SSTypography.bodyFamily,
                    fontSize: 13.5,
                    fontWeight: FontWeight.w600,
                    color: brand,
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ─── Section label ────────────────────────────────────────────────────────────

class _SectionLabel extends StatelessWidget {
  const _SectionLabel(this.text, {required this.dark});
  final String text;
  final bool dark;

  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: TextStyle(
        fontFamily: SSTypography.monoFamily,
        fontSize: 10.5,
        letterSpacing: 1.8,
        fontWeight: FontWeight.w500,
        color: dark ? SSColors.mutedDark : SSColors.muted,
      ),
    );
  }
}
