import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../core/theme/app_theme.dart';
import '../../../shared/widgets/ss_primitives.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final dark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: dark ? SSColors.bgDark : SSColors.paper,
      body: SafeArea(
        child: Column(
          children: [
            SSTopBar(
              title: 'Terms of Service',
              leading: SSIconBtn(
                icon: Icons.arrow_back_ios_new_rounded,
                onTap: () => context.pop(),
              ),
            ),
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.fromLTRB(20, 8, 20, 40),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _Section(
                      title: 'Not medical advice',
                      body: 'Clera provides ingredient safety information for educational purposes only. Nothing in the app constitutes medical, nutritional, or pharmaceutical advice. Always consult a qualified professional before making health decisions.',
                      dark: dark,
                    ),
                    _Section(
                      title: 'Accuracy',
                      body: 'Safety scores and ingredient analysis are generated by AI and may contain errors. Clera makes no warranty as to accuracy or completeness. Do not rely solely on Clera for allergy or medical decisions.',
                      dark: dark,
                    ),
                    _Section(
                      title: 'Acceptable use',
                      body: 'You may not use Clera to scrape data, reverse-engineer the service, or submit fraudulent scans. Accounts found abusing the service will be suspended.',
                      dark: dark,
                    ),
                    _Section(
                      title: 'Subscriptions',
                      body: 'Pro and Family subscriptions are billed through the App Store or Play Store. Cancellations take effect at the end of the current billing period. No refunds are issued for partial periods.',
                      dark: dark,
                    ),
                    _Section(
                      title: 'Limitation of liability',
                      body: 'Clera is provided "as is". To the maximum extent permitted by law, Clera shall not be liable for any damages arising from use of the app.',
                      dark: dark,
                    ),
                    _Section(
                      title: 'Contact',
                      body: 'Clera · legal@clera.app\nLast updated: April 2026',
                      dark: dark,
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _Section extends StatelessWidget {
  const _Section({required this.title, required this.body, required this.dark});
  final String title, body;
  final bool dark;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyle(
              fontFamily: SSTypography.displayFamily,
              fontWeight: FontWeight.w600,
              fontSize: 16,
              color: dark ? SSColors.inkDark : SSColors.ink,
            ),
          ),
          const SizedBox(height: 6),
          Text(
            body,
            style: TextStyle(
              fontFamily: SSTypography.bodyFamily,
              fontSize: 14,
              height: 1.6,
              color: dark ? SSColors.ink2Dark : SSColors.ink2,
            ),
          ),
        ],
      ),
    );
  }
}
